projects:
  nuxt3:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ap-northeast-1
        apiId: xo7p42opqjh4ppkpdnkgqukuxy
        maxDepth: 2
extensions:
  amplify:
    version: 3
