// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/6/2024, 12:28:23 AM
const configMerger = require("/Users/johoric/zihao/nuxt3/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/johoric/zihao/nuxt3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/johoric/zihao/nuxt3/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/johoric/zihao/nuxt3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/johoric/zihao/nuxt3/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/johoric/zihao/nuxt3/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/johoric/zihao/nuxt3/plugins/**/*.{js,ts,mjs}","/Users/johoric/zihao/nuxt3/composables/**/*.{js,ts,mjs}","/Users/johoric/zihao/nuxt3/utils/**/*.{js,ts,mjs}","/Users/johoric/zihao/nuxt3/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/johoric/zihao/nuxt3/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/johoric/zihao/nuxt3/app.config.{js,ts,mjs}"] }));

module.exports = config
